import "bootstrap/dist/css/bootstrap.css";
import "./global.css";
import Layout from '../components/layout';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <Layout>{children}</Layout>;
}
