export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import Layout from "@/components/layout";
import "bootstrap/dist/css/bootstrap.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <Layout>{children}</Layout>;
}
