<<<<<<< HEAD
import "bootstrap/dist/css/bootstrap.css";
import "./global.css";
import Layout from '../components/layout';

=======
>>>>>>> Initial commit from Create Next App
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
<<<<<<< HEAD
=======
import Layout from "@/components/layout";
import "bootstrap/dist/css/bootstrap.css";
>>>>>>> Initial commit from Create Next App

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <Layout>{children}</Layout>;
}
